TAUR-1261 Update configure-infrastructure-ami to use salt master
* Read minion ID from file created by Rakefile
* Set master to salt.numenta.com explicitly in /etc/salt/minion
* Strip out salt-solo references
* Update resolv.conf to search numenta.com by default
* Retry if first salt run fails

diff --git a/infrastructure/ami-tools/packer-scripts/configure-infrastructure-ami b/infrastructure/ami-tools/packer-scripts/configure-infrastructure-ami
--- a/infrastructure/ami-tools/packer-scripts/configure-infrastructure-ami
+++ b/infrastructure/ami-tools/packer-scripts/configure-infrastructure-ami
@@ -40,20 +40,29 @@ mv /tmp/secretsauce.repo /etc/yum.repos.d
 echo "Cleaning yum..."
 yum clean all
 
-echo "Installing minion formulas..."
-yum install -y minion-saltcellar
-
 # Ensure we have the latest glibc to protect against the GHOST vulnerability
 echo "Updating glibc"
 yum install -y glibc
 
+echo "Old minion_id"
+cat /etc/salt/minion_id
+
 echo "Stopping Salt..."
 service salt-minion stop
 
+echo "Setting search list in /etc/resolv.conf to numenta.com"
+sed 's/^search .*/search numenta.com/g' /etc/resolv.conf -i''
+cat /etc/resolv.conf
+host salt.numenta.com
+
 echo "Configuring Salt minion_id"
 echo
-echo "Setting Salt minion_id to role-infrastructure"
-echo role-infrastructure-ami > /etc/salt/minion_id
+echo "Setting Salt minion_id: $(cat /tmp/infrastructure_minion_id)"
+cat /tmp/infrastructure_minion_id > /etc/salt/minion_id
+
+echo "Setting salt master name"
+sed 's/^#master: salt/master: salt.numenta.com/g' /etc/salt/minion -i''
+grep '/^master:/' /etc/salt/minion
 
 echo "Purging salt minion key data..."
 rm -fr /etc/salt/pki/minion/*
@@ -61,9 +70,25 @@ rm -fr /etc/salt/pki/minion/*
 echo "Restarting salt minion..."
 service salt-minion restart
 
+echo "Wait for master to sign key..."
+sleep 10
+
+# echo
+# echo "Test salt config"
+# salt-call state.highstate test=True
+
+echo
 echo "Running Salt..."
-salt-call --local state.highstate -l debug
+salt-call state.highstate
 saltcode=$?
+
+if [ "${saltcode}" != 0 ]; then
+  sleep 15
+  echo "RETRY FAILED SALT RUN"
+  salt-call state.highstate
+  saltcode=$?
+fi
+
 echo
 echo "Salt run return code: ${saltcode}"
 exit "${saltcode}"
